application: captain-pasty
version: captain-pasty
runtime: python27
api_version: 1
threadsafe: true

libraries:

  - name: pytz
    version: latest

  - name: PyCrypto
    version: latest

handlers:

  - url: /static/
    static_dir: static
    login: required
    secure: always

  - url: /_ah/(mapreduce|queue|warmup).*
    script: project.wsgi.application
    login: admin

  - url: /api/.*
    script: pasty.api.app

  - url: /.*
    script: project.wsgi.application
    login: required
    secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

  - ^node_modules/
  - ^static/src/
  - ^libs/.*\.(egg|dist)-info
